### ISSUE TITLE
point cloud segment autoencoding

### ISSUE THREAD

**Issue by GeeeG** [dahliau/DPDist#2]
Hi @dahliau , nice work!
I saw in the supplementary material when you the autoencoding task (comparing with Chamfer), the results are quite sparse. My question is that if both of my input and output point clouds are uniformly sampled with Farthest point sampling, would DPDist do a better job? 
Thank you and look forward to your code!

**Comment by dahliau** [comment]
Hi @GeeeG , thanks!
One of the benefits of using DPDist is its ability to be sample invariance. For auto-encoder outputs, this property is less wanted. The output point could might be too sparse because DPDist can estimate the same surface from fewer points (so some output points may result in a dense crowding, as shown in the supplementary).
Take into consideration that DPDist is built on implicit function. Therefore, DPDist itself is a type of auto-encoder (some consider the implicit neural network as a decoder, as its output is an implicit function of the wanted surface).
